language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

jdk:
  - oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew build

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
